name: Auto request changes
on: [pull_request] # Support only pull_request event.

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MIX_ENV: test
  ImageOS: ubuntu20 # equivalent to runs-on ubuntu-20.04

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12'

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Format Code
        run: mix format

      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: mix format
